### ISSUE TITLE
Can you add a brief setup and usage instruction?

### ISSUE THREAD

**Issue by jianchanghuang** [RovelMan/active-learning-framework#1]
That would be very helpful. Thank you!

**Comment by RovelMan** [comment]
Hi! I have updated the README with information about how to set up and run a simple experiment.
Open up the active_learning_framework.ipynb in Google colab (see link below) and follow the tutorial for running active learning with object detection using Faster R-CNN on the yymnist digit dataset.  https://github.com/YunYang1994/yymnist
Link to the shared file: https://colab.research.google.com/drive/1HemwVRUmJkTRaZVykTrcVjRMmnpuoVQ1?usp=sharing 

I will update the README and add more information very soon that will explain the framework in more detail and give a better explanation on how to run custom experiments. Hopefully at the end of this upcoming week.

**Comment by jianchanghuang** [comment]
Appreciate it!
